# Generated by Django 5.1.3 on 2024-11-11 13:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0003_alter_user_date_of_birth_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_of_birth', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بایو')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog_account_images/', verbose_name='تصویر پروفایل')),
                ('job', models.CharField(max_length=250, verbose_name='شغل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('groups', models.ManyToManyField(blank=True, null=True, related_name='personal_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, null=True, related_name='personal_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'کاربر بلاگ',
                'verbose_name_plural': 'کاربر های بلاگ',
                'ordering': ['-username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddIndex(
            model_name='bloguser',
            index=models.Index(fields=['-username'], name='blog_blogus_usernam_227bae_idx'),
        ),
    ]
