# Generated by Django 5.1.3 on 2024-11-11 13:51

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_bloguser_date_of_birth_alter_bloguser_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
