# Generated by Django 5.1.3 on 2024-11-11 14:00

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_bloguser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog/account_images/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='blog/post_images/'),
        ),
    ]
